### ISSUE TITLE
Contributor mention

### ISSUE THREAD

**Issue by jugendhacker** [adrianinsaval/onedrive_tray-git#1]
I would like to mention you in the AUR as Contributor.... what should I write as name and email?

**Comment by adrianinsaval** [comment]
Thanks, my name is Adrián Insaurralde
email: adrianinsaval at gmail dot com

Be aware of this before pushing the changes to AUR please: https://github.com/DanielBorgesOliveira/onedrive_tray/pull/7

**Comment by jugendhacker** [comment]
DanielBorgesOliveira/onedrive_tray#7 was merged, I'll update the AUR package now
